name: Build and deploy WebApp 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
      id-token: write
      contents: read
    
env:
  AZURE_RESOURCE_GROUP: WIF-Example
  AZURE_WEBAPP_NAME: moimxysf34d    # set this to your application's name - test
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.101'   


jobs:
  build:    
    runs-on: ubuntu-latest

    
    steps:      
      - uses: actions/checkout@v2
      
      - name: OIDC Login to Azure 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: false


      - name: Azure CLI Action
        uses: Azure/cli@v2.1.0
        with:
          # Specify the script here
          inlineScript: |
             az group list -o table

          
        


      - name: Azure logout
        run: az logout
